### ISSUE TITLE
Update README.

### ISSUE THREAD

**Issue by kevindecapite** [kevindecapite/php-sweph#28]
Now that we're using tagged releases, the general public should be aware not to use `master` in their production environments as it could contain bugs or other untested features.

Also add a note regarding the "gitflow" development process.

**Comment by aloistr** [comment]
I have updated readme, remove the missing functions settings.
Please be aware that the implemented missing functions 
swe_heliacal_ut
swe_heliacal_pheno_ut
swe_vis_limit_mag
are untested. I have never used them, because I do not understand heliacal stuff and shy away with everything having to do with atmosphere in visibility.
A test should compare C output and php output, for the same input parameters.

One function, swe_heliacal_angle, exists in swephexp.h as an exported function, but is undocumented.
I have not included it.

**Comment by kevindecapite** [comment]
Thank you. I created an issue for writing the tests for these new functions:

https://github.com/cyjoelchen/php-sweph/issues/31
