### ISSUE TITLE
ephe file sin ./sweph/ephe

### ISSUE THREAD

**Issue by aloistr** [kevindecapite/php-sweph#32]
I suggest we move the se*18.se1 and sefstars.txt into ./sweph/ephe and update all tests to include
swe_set_ephe_path('./sweph/ephe')
I also suggest to not use SEFLG_MOSEPH in any test, but use SEFLG_SWIEPH.
Where appropriate, the flag should also contain SEFLG_SPEED for all functions which have speed in the
result vector.

**Comment by kevindecapite** [comment]
I failed to mention in my instructions that once a PR is opened against an issue, the issue can be closed. The reason is so that there are not 2 places where a conversation is taking place covering the same subject. Equally important, then, is to _link_ the original issue to the PR and vice-versa. That way there is continuity/linkage between the issue and the PR.

Here is how to do that:

1. Copy the issue URL from your browser.
2. Paste it into the PR description or some comment field (usually with "Refs:" as a label, but that's not important).

_Github will automatically create a link from the PR to the issue, and another link from the issue to the PR._

Then you know it's safe to close the issue, and all further discussion should take place in the PR from then on.

My apologies for not making this more clear from the beginning.
