### ISSUE TITLE
fixing bugs in master branch

### ISSUE THREAD

**Issue by aloistr** [kevindecapite/php-sweph#53]
I fixed a bug in swe_deltat_ex, the return variable is dt and not tjd_et.
This function was only added on 16 July 21, it is unlikely that it is used in production anywhere.
This justifies immediate release to the master branch, even when it potentially breaks API usage.

I also fixed to related test cases.
While swe_deltat and swe_deltat_ex retung deltat in units of days, the tests should reflect the fact that deltat is usually give in units of time seconds.

**Comment by kevindecapite** [comment]
Thank you for catching that. I published a new release, now @ 3.0.1, which includes the latest fixes you have applied over the last week or so:

https://github.com/cyjoelchen/php-sweph/releases/tag/3.0.1

The repository's main page (i.e. README) instructs consumers to install the latest release rather than `master`. This is preferred so we can continue to merge our work into `master` whenever we like without having to worry about it breaking anyone's application (in case we introduce a bug accidentally).

The tags/releases allow us to more formally declare that the repository is in a working state at that specific point in time.
