### ISSUE TITLE
branch se2.10.02

### ISSUE THREAD

**Issue by aloistr** [kevindecapite/php-sweph#60]
I think branch se2.10.02 is complete, also with simple tests or the new swe_solcross function group.

**Comment by kevindecapite** [comment]
I reviewed and everything checks out. I wrapped the test output of `swe_mooncross_node` in the `Format::round()` method due to the potential of discrepancies with the near zero value of the latitude.

We now have a PHP release of 3.1.0 which includes these new functions:
https://github.com/cyjoelchen/php-sweph/releases/tag/3.1.0
