### ISSUE TITLE
Compile in Windows 10

### ISSUE THREAD

**Issue by blucobalto** [kevindecapite/php-sweph#79]
Hi,
please, how can I compile in Windows 10 and Visual Studio 2019 (or other compiler)?
I have installed php and php-devel but the instructions for php don't work in Windows.

Thanks a lot,
Blu

**Comment by kevindecapite** [comment]
See #50 which may provide some help for you. I don't use Windows and haven't tried to compile the extension on that OS, though it should be possible. 

See also:

https://www.php.net/manual/en/install.windows.building.php

https://wiki.php.net/internals/windows/stepbystepbuild

These will provide you with more information on how to compile PHP on Windows generally. That knowledge should assist you in building the extension.

**Comment by blucobalto** [comment]
Hi,
I tried to follow the instructions but I can only compile the php. When I try to compile the php-sweph extension it doesn't seem to recognize it. If I understand correctly, the config.w32 file is missing; this file is used for Windows.
Unfortunately I am unable to generate a correct config.w32.

To compile I found this url which updates the information for VS2019:
https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2

Thanks a lot,
Blu

**Comment by blucobalto** [comment]
Hi,
I solved by installing WSL (Ubuntu) for Windows 10.

Thanks a lot,
Blu

**Comment by rpuig** [comment]
Hello , 

I am not very proficient on building .so extensions and I would find it very helpful if you were to share the steps you have followed to achieve this. I am using Windows 10 as well for my astro developments . I am a hobbyist in the domain and have no computer programming education other than my spaghetti php,javascript of the sort. 

Which files are necessary to generate the **swephp.so** extension on this operating system? If I use a virtual machine like VMware with Debian 10, will i be able to use the php extension on a xampp/lamp server on my Windows machine or will i need to stick to the same OS?

Sorry if these questions sound too newbye, but compiling is for me the most complex aspect in programming up till now, i had been able to use php and javascript without too much compilation, until i came across Swiss ephemeris and realized i need to compile from source.

Cheers

**Comment by kevindecapite** [comment]
What exactly is your environment? If you are using Debian on a VM, then it doesn't matter if the host OS is Windows, macOS or Linux, etc. You would just follow the instructions provided in the README of the repository's homepage:

https://github.com/cyjoelchen/php-sweph

This would be true even if running Xampp on the VM since the server environment in this case is Debian/Linux. Please note that Xampp may have special rules for enabling a custom extension. I'm not familiar with using it so you'll have to consult their documentation to know for certain.

However, if you are running Xampp directly in your Windows environment, then you will need to review the discussion above on this page for compiling the swephp extension on Windows.

**Comment by rpuig** [comment]
> What exactly is your environment? If you are using Debian on a VM, then it doesn't matter if the host OS is Windows, macOS or Linux, etc. You would just follow the instructions provided in the README of the repository's homepage:
> 
> https://github.com/cyjoelchen/php-sweph
> 
> This would be true even if running Xampp on the VM since the server environment in this case is Debian/Linux. Please note that Xampp may have special rules for enabling a custom extension. I'm not familiar with using it so you'll have to consult their documentation to know for certain.
> 
> However, if you are running Xampp directly in your Windows environment, then you will need to review the discussion above on this page for compiling the swephp extension on Windows.

Hello Kevin, 

Thank you for your help. I have installed a VM with a lamp stack from Bitnami, and i am now going to try the .so extension that Allen Edwall has compiled , and that its usable on a linux environment.

I had to switch to Linux as I was not able to continue my development due to a sudden requirement from my browsers for a SSL certificate which I was not able to install with mkcert on windows as mkcert seems to have a bug in the date of expiry from the automatic root certificate and another option was to use a generic localhost certificate which is a security risk. So as you mention its better to use a VM.

Best regards

Ramon
