### ISSUE TITLE
Where to find swephp.so 

### ISSUE THREAD

**Issue by rpuig** [kevindecapite/php-sweph#83]
hello,

first, thank you for this php translation of sweph.c !

I would like to test the swephp library but I havent been able to use it because I cant find swephp.so and link it to my php server via the php.ini file.

Do I need to compile through gcc? I am running the example.php on windows 10 via a xampp local stack. 

Kind regards

**Comment by aloistr** [comment]
This might help you as work-around
https://github.com/cyjoelchen/php-sweph/issues/79

**Comment by aedwall33** [comment]
I have uploaded a "swephp.so" file that works on my Bluehost.com account Linux web server. You may download it at:

astrowin.org/anonymous/swephp.so

I have also uploaded a small test file in order to check your installation:

astrowin.org/anonymous/test_SE.php

You can check your results with what is displayed here:

https://astrowin.org/sweph/test_SE.php

Of course, your must tell your PHP where to find the .so file via you php.ini file or your .user.ini file.

**Comment by rpuig** [comment]
Wow Allen, thank you so much! You saved me the probably didactic trouble of learning to compile php extensions on linux.  I did find  Alois link very helpful aswell, since I have a Vmware LAMP stack virtual machine, but I was having problems with the file sharing and other issues, which slowed me down . Now with this .so I am going to be able to port all my windows tests to linux which is my hosting server OS.  I hope you are well. And thank you very much for your invaluable contribution to the advancement of astrological science.
