### ISSUE TITLE
Compile warning swephp.c

### ISSUE THREAD

**Issue by AstroSign-Dev** [kevindecapite/php-sweph#88]
Version 4.0.8
/home/user/php-sweph/swephp.c: In function ‘zif_swe_house_name’:
/home/user/php-sweph/swephp.c:2888:14: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
 2888 |         name = swe_house_name(hsys[0]);

**Comment by kevindecapite** [comment]
Thank you for mentioning this. I noticed it when updating to the latest version of SE but forgot to address it. It's fixed in `master` via this commit: https://github.com/cyjoelchen/php-sweph/commit/759d76d001ffcbacb8914a809ef07815f4398382

Since the extension is working fine with the warning, I'll wait on releasing another version of it until a few more bug fixes and/or features are implemented.

For proof, open any of the test runs from this page and expand the "Build Extension" step:

https://github.com/cyjoelchen/php-sweph/actions/runs/3114010205

**Comment by kevindecapite** [comment]
Closing as this is resolved in:
- https://github.com/cyjoelchen/php-sweph/releases/tag/4.0.9
